# Generated by Django 3.0.7 on 2020-07-14 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='area_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='userINFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='exercises_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=30)),
                ('duration', models.IntegerField()),
                ('rest', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('dateposted', models.DateField()),
                ('area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='budy.area_Db')),
            ],
            options={
                'ordering': ['exercise'],
            },
        ),
    ]
