# Generated by Django 3.1 on 2020-08-25 10:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ExercisesDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=30)),
                ('duration', models.IntegerField()),
                ('rest', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('dateposted', models.DateField(default=datetime.datetime(2020, 8, 25, 10, 19, 40, 452392, tzinfo=utc))),
                ('area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='budy.areadb')),
            ],
            options={
                'ordering': ['exercise'],
            },
        ),
    ]
