# Generated by Django 3.0.8 on 2020-08-02 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budy', '0004_auto_20200802_0158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
